---@author java3east [Discord: java3east]

---Replaces the char of a string at a given index.
---@param str string
---@param char string
---@param index integer
---@return string
function string.replaceCharAt(str, char, index)
    local before = ""
    if index > 1 then
        before = str:sub(1, index - 1)
    end

    local after = ""
    if index < str:len() then
        after = str:sub(index + 1, str:len())
    end

    return before .. char .. after
end

function string.charAt(str, index)
    return str:sub(index, index)
end

---@private
function string.__replaceWithRandomFromCharSet(str, charset, index)
    string.replaceCharAt(
        str,
        string.charAt(
            charset,
            math.random(
                charset:len()
            )
        ),
        index
    )
end

---Generates & returns a new random string generated by the given pattern.
---@param pattern string a => lowerCase; A => upperCase; 0 => number; ! => symbols; * => any;
---@return any
function string.random(pattern)
    local str = pattern

    local length = string.len(str)
    local lowerCase = "abcdefghijklmnopqrstuvwxyz"
    local upperCase = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
    local numbers = "0123456789"
    local symbols = "!@#$%&()*+-,./\\:;<=>?^[]{}"

    for i = 1, length, 1 do
        local char = str:sub(i, i)
        if char == "A" then
            string.__replaceWithRandomFromCharSet(str, upperCase, i)
        elseif char == "a" then
            string.__replaceWithRandomFromCharSet(str, lowerCase, i)
        elseif char == "0" then
            string.__replaceWithRandomFromCharSet(str, numbers, i)
        elseif char == "!" then
            string.__replaceWithRandomFromCharSet(str, symbols, i)
        elseif char == "*" then
            string.__replaceWithRandomFromCharSet(str, lowerCase .. upperCase .. numbers .. symbols, i)
        end
    end

    return str
end